import { ILevelData } from '../types/interface';

export const levelsData: ILevelData[] = [
    {
        levelNumber: 1,
        title: 'Select elements by their type',
        selectorName: 'Type Selector',
        doThis: 'Select the plates',
        selector: 'plate',
        syntax: 'A',
        hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
        examples: [
            '<strong>div</strong> selects all <tag>div</tag> elements.',
            '<strong>p</strong> selects all <tag>p</tag> elements.',
        ],
        boardMarkup: ['<plate />', '<plate />'],
        realMarkup: `<plate></plate><plate></plate>`,
        answer: 'plate plate',
    },
    {
        levelNumber: 2,
        title: '2Select elements by their type',
        selectorName: '2Type Selector',
        doThis: 'Select element by their id',
        selector: '#fancy',
        syntax: 'A',
        hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
        examples: [
            '<strong>div</strong> selects all <tag>div</tag> elements.',
            '<strong>p</strong> selects all <tag>p</tag> elements.',
        ],
        boardMarkup: ['<plate />', '<plate id="fancy" />', '<plate />'],
        realMarkup: `<plate></plate><plate id='fancy'></plate><plate></plate>`,
        answer: 'plate',
    },
    {
        levelNumber: 3,
        title: '3Select elements by their type',
        selectorName: 'Select apple on the plate',
        doThis: '3Select the plates',
        selector: 'plate apple',
        syntax: 'A',
        hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
        examples: [
            '<strong>div</strong> selects all <tag>div</tag> elements.',
            '<strong>p</strong> selects all <tag>p</tag> elements.',
        ],
        boardMarkup: ['<plate />', '<plate>', '<apple />', '</plate>', '<apple />'],
        realMarkup: `<plate></plate><plate><apple></apple></plate><apple></apple>`,
        answer: 'apple',
    },
    {
        levelNumber: 4,
        title: '4Select elements by their type',
        selectorName: 'Select apple on the fancy plate',
        doThis: '4Select the plates',
        selector: '#fancy apple',
        syntax: 'A',
        hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
        examples: [
            '<strong>div</strong> selects all <tag>div</tag> elements.',
            '<strong>p</strong> selects all <tag>p</tag> elements.',
        ],
        boardMarkup: ['<plate>', '<apple />', '</plate>', '<plate id="fancy">', '<apple />', '</plate>'],
        realMarkup: `<plate><apple></apple></plate><plate id='fancy'><apple></apple></plate>`,
        answer: 'apple',
    },
    {
        levelNumber: 5,
        title: '5Select elements by their type',
        selectorName: 'Select bento',
        doThis: '5Select the plates',
        selector: 'bento',
        syntax: 'A',
        hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
        examples: [
            '<strong>div</strong> selects all <tag>div</tag> elements.',
            '<strong>p</strong> selects all <tag>p</tag> elements.',
        ],
        boardMarkup: ['<plate>', '<apple/>', '</plate>', '<plate />'],
        realMarkup: `<plate><bento></bento></plate><plate><apple></apple></plate><apple></apple>`,
        answer: 'bento',
    },
    // {
    //     levelNumber: '6',
    //     title: '6Select elements by their type',
    //     selectorName: '6Type Selector',
    //     doThis: '6Select the plates',
    //     selector: 'plate',
    //     syntax: 'A',
    //     hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
    //     examples: [
    //         '<strong>div</strong> selects all <tag>div</tag> elements.',
    //         '<strong>p</strong> selects all <tag>p</tag> elements.',
    //     ],
    //     boardMarkup: '<plate/><plate/>',
    // },
    // {
    //     levelNumber: '7',
    //     title: '7Select elements by their type',
    //     selectorName: '7Type Selector',
    //     doThis: '7Select the plates',
    //     selector: 'plate',
    //     syntax: 'A',
    //     hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
    //     examples: [
    //         '<strong>div</strong> selects all <tag>div</tag> elements.',
    //         '<strong>p</strong> selects all <tag>p</tag> elements.',
    //     ],
    //     boardMarkup: '<plate/><plate/>',
    // },
    // {
    //     levelNumber: '8',
    //     title: '8Select elements by their type',
    //     selectorName: '8Type Selector',
    //     doThis: '8Select the plates',
    //     selector: 'plate',
    //     syntax: 'A',
    //     hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
    //     examples: [
    //         '<strong>div</strong> selects all <tag>div</tag> elements.',
    //         '<strong>p</strong> selects all <tag>p</tag> elements.',
    //     ],
    //     boardMarkup: '<plate/><plate/>',
    // },
    // {
    //     levelNumber: '9',
    //     title: '9Select elements by their type',
    //     selectorName: '9Type Selector',
    //     doThis: '9Select the plates',
    //     selector: 'plate',
    //     syntax: 'A',
    //     hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
    //     examples: [
    //         '<strong>div</strong> selects all <tag>div</tag> elements.',
    //         '<strong>p</strong> selects all <tag>p</tag> elements.',
    //     ],
    //     boardMarkup: '<plate/><plate/>',
    // },
    // {
    //     levelNumber: '10',
    //     title: '10 Select elements by their type',
    //     selectorName: '10 Type Selector',
    //     doThis: '10 Select the plates',
    //     selector: 'plate',
    //     syntax: 'A',
    //     hint: 'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <tag>div</tag>, <tag>p</tag> and <tag>ul</tag> are all different element types.',
    //     examples: [
    //         '<strong>div</strong> selects all <tag>div</tag> elements.',
    //         '<strong>p</strong> selects all <tag>p</tag> elements.',
    //     ],
    //     boardMarkup: '<plate/><plate/>',
    // },
];
